# Generated by Django 3.2.6 on 2021-08-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
    ]
