# Generated by Django 3.2.6 on 2021-08-26 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeditem',
            name='is_custom',
        ),
        migrations.AddField(
            model_name='item',
            name='custom_item_kitchen',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.kitchen'),
        ),
        migrations.AlterField(
            model_name='item',
            name='upc',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
