# Generated by Django 3.2.6 on 2021-08-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210826_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='join_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='public_access_uuid',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('PJR', 'Pending Join Request'), ('PI', 'Pending Invitation'), ('AM', 'Active Membership')], default='AM', max_length=3),
        ),
    ]
