# Generated by Django 3.2.6 on 2021-08-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210829_1225'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'kitchen')},
        ),
    ]
