# Generated by Django 4.0.1 on 2022-02-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_storeditem_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='backgrounds'),
        ),
        migrations.AlterField(
            model_name='item',
            name='upc',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
